# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20170604_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='title',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together=set([('country', 'city', 'street')]),
        ),
        migrations.AlterUniqueTogether(
            name='name',
            unique_together=set([('first_name', 'last_name')]),
        ),
    ]
