# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20170604_1421'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='name',
            unique_together=set([('title', 'first_name', 'last_name')]),
        ),
    ]
