branch-defaults:
  master:
    environment: LowCost-env
    group_suffix: null
global:
  application_name: addressbook
  branch: null
  default_ec2_keyname: null
  default_platform: python
  default_region: eu-west-1
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
